repos:
  - repo: https://github.com/psf/black
    rev: 23.12.0 # Use latest stable version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
